# Default values for keda-hpa-activemq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

suffix: ""

enabled: true

scaleTargetRef:
  apiVersion: "apps/v1"                                       # Optional. Default: apps/v1
  kind: "Deployment"                                          # Optional. Default: Deployment
  name: ""                                                    # Mandatory. Must be in the same namespace as the ScaledObject
  envSourceContainerName: ".spec.template.spec.containers[0]" # Optional. Default: .spec.template.spec.containers[0]

pollingInterval: 30                                          # Optional. Default: 30 seconds
cooldownPeriod: 300                                         # Optional. Default: 300 seconds
idleReplicaCount: 0                                           # Optional. Default: ignored, must be less than minReplicaCount
minReplicaCount: 1                                           # Optional. Default: 0
maxReplicaCount: 100                                         # Optional. Default: 100

fallback: # Optional. Section to specify fallback options
  failureThreshold: 3                                         # Mandatory if fallback section is included
  replicas: 6                                                 # Mandatory if fallback section is included

behavior: # Optional. Section to specify advanced options
  restoreToOriginalReplicaCount: false                        # Optional. Default: false
  stabilizationWindowSeconds: 300
  type: Percent
  value: 100
  periodSeconds: 15

triggers:
  managementEndpoint: ""
  destinationName: ""
  brokerName: ""
  targetQueueSize: "50"
  authentication: ""