{{ if .Values.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: activemq-scaledobject-{{ .Values.suffix }}
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: {{ .Values.scaleTargetRef.apiVersion }}  # Optional. Default: apps/v1
    kind: {{ .Values.scaleTargetRef.kind }}         # Optional. Default: Deployment
    name: {{ .Values.scaleTargetRef.name }}        # Mandatory. Must be in the same namespace as the ScaledObject
    envSourceContainerName: {{ .Values.scaleTargetRef.envSourceContainerName }}        # Optional. Default: .spec.template.spec.containers[0]
  pollingInterval:  {{ .Values.pollingInterval }}                               # Optional. Default: 30 seconds
  cooldownPeriod:   {{ .Values.cooldownPeriod }}                              # Optional. Default: 300 seconds
  idleReplicaCount: {{ .Values.idleReplicaCount }}                               # Optional. Default: ignored, must be less than minReplicaCount
  minReplicaCount:  {{ .Values.minReplicaCount }}                                # Optional. Default: 0
  maxReplicaCount:  {{ .Values.maxReplicaCount }}                              # Optional. Default: 100
#  fallback:                                          # Optional. Section to specify fallback options
#    failureThreshold: {{ .Values.fallback.failureThreshold }}                              # Mandatory if fallback section is included
#    replicas: {{ .Values.fallback.replicas }}                                     # Mandatory if fallback section is included
  advanced:                                          # Optional. Section to specify advanced options
    restoreToOriginalReplicaCount: {{ .Values.behavior.restoreToOriginalReplicaCount }}        # Optional. Default: false
    horizontalPodAutoscalerConfig:                   # Optional. Section to specify HPA related options
      behavior:                                      # Optional. Use to modify HPA's scaling behavior
        scaleDown:
          stabilizationWindowSeconds: {{ .Values.behavior.stabilizationWindowSeconds }}
          policies:
          - type: {{ .Values.behavior.type }}
            value: {{ .Values.behavior.value }}
            periodSeconds: {{ .Values.behavior.periodSeconds }}
  triggers:
    - type: activemq
      metadata:
        managementEndpoint: {{ .Values.triggers.managementEndpoint }}
        destinationName: {{ .Values.triggers.destinationName }}
        brokerName: {{ .Values.triggers.brokerName }}
        targetQueueSize: {{ .Values.triggers.targetQueueSize | quote }}
        #restAPITemplate: https://{{ .Values.triggers.managementEndpoint }}/api/jolokia/read/org.apache.activemq:type=Broker,brokerName={{ .Values.triggers.brokerName }},destinationType=Queue,destinationName={{ .Values.triggers.destinationName }}/QueueSize
      authenticationRef:
        name: {{ .Values.triggers.authentication }}
{{ end }}