name: Build Documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Get mono
      run: |
        sudo apt-get -y install gnupg ca-certificates
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt-get update
        sudo apt -y dist-upgrade
        sudo apt -y install mono-runtime mono-devel msbuild

    - name: Get docfx
      run: |
        curl -L https://github.com/dotnet/docfx/releases/latest/download/docfx.zip -o docfx.zip
        unzip -d $HOME/.docfx docfx.zip

    - name: Build docs
      run:  |
        mono $HOME/.docfx/docfx.exe Documentation/docfx.json build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: Documentation/_site
